export { Home } from './Home';
export { Intro } from './Intro';
export { Searching } from './Searching';
export { SearchResult } from './SearchResult';
export { Writing1 } from './Writing1';
export { Writing2 } from './Writing2';
// export { Writing3 } from './Writing3';
// export { Writing4 } from './Writing4';
export { Writing6 } from './Writing6';
export { Faq } from './Faq';
export { Login } from './Login';
export { Join } from './Join';
export { MyPage } from './MyPage';
export { LawyerMain } from './LawyerMain';
export { LawyerProfile } from './LawyerProfile';
export { LawyerReview } from './LawyerReview';
